import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:rest_api/product.dart';


class UserService {
  static const String url = 'https://reqres.in/api/unknown';

  static Future<Autogenerated> fetchUserData() async {
    final response = await http.get(Uri.parse(url));

    if (response.statusCode == 200) {
      return Autogenerated.fromJson(json.decode(response.body));
    } else {
      throw Exception('Failed to load user data');
    }
  }
}


class LoginService {
  static const String loginUrl = 'https://reqres.in/api/login';

  static Future<String> login(String email, String password) async {
    final response = await http.post(
      Uri.parse(loginUrl),
      headers: {'Content-Type': 'application/json'},
      body: jsonEncode({
        'email': email,
        'password': password,
      }),
    );

    if (response.statusCode == 200) {
      final data = jsonDecode(response.body);
      return data['token']; // Return token
    } else {
      throw Exception('Failed to login');
    }
  }
}
